uno-isqa-8950/uno-cpi

.idea/workspace.xml
cap_2018/UnoCPI/UnoCPI/urls.py
cap_2018/UnoCPI/home/templates/home/base_home.html
cap_2018/UnoCPI/home/urls.py

Minor changes on UI

---

.idea/workspace.xml
UnoCPI/settings.py
UnoCPI/urls.py
account/admin.py
account/apps.py
account/forms.py
account/models.py
account/templates/account/login.html
account/templates/registration/logged_out.html
account/templates/registration/login.html
account/templates/registration/password_change_done.html
account/templates/registration/password_change_form.html
account/templates/registration/password_reset_complete.html
account/templates/registration/password_reset_confirm.html
account/templates/registration/password_reset_done.html
account/templates/registration/password_reset_email.html
account/templates/registration/password_reset_form.html
account/tests.py
account/urls.py
account/views.py

Login Logout and reset password features in the app

check this commit

---

home/templates/home/base_home.html

Reverts uno-isqa-8950/uno-cpi#82

Revert "mobile view fix"

---

UnoCPI/urls.py
account/templates/registration/login.html
account/templates/registration/password_reset_complete.html
account/templates/registration/password_reset_form.html
account/urls.py
home/templates/home/CpiHome.html
home/templates/home/base_home.html
home/templates/home/campus_partner_register.html
home/urls.py

URL issues fixed

---

home/templates/home/campus_partner_profile.html
partners/forms.py
partners/urls.py
partners/views.py

Added new Url and render function for showing profiles of CampusPartner

---

home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
partners/forms.py
projects/forms.py
projects/templates/projects/community_partner_projects.html
projects/templates/projects/community_partner_projects_edit.html
projects/views.py

Community user ability to enter hours and volunteers count.
Fixed the placeholder for contact on Campus and Community partner registration pages.
Fixed url issue for campus view projects

Community user project edit

---

UnoCPI/settings.py
account/forms.py
account/templates/registration/login.html
account/views.py
home/admin.py
home/forms.py
home/models.py
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/communityuser_register_done.html
home/views.py
partners/templates/partners/campus_partner_user_profile.html

#Email Login 
#Signup pages fixed to use Email 
#Login decorators fixed to lock down views

Test email auth

---

UnoCPI/settings.py
partners/templates/registration/community_partner_register.html

Community Partner Register Page UI Fix

community Partner Register UI Fix

---

UnoCPI/settings.py
home/templates/home/base_home.html
home/templates/reports/14ProjectPartnerInfo.html
home/templates/reports/projectreport.html
home/urls.py
home/views.py
requirements.txt

Completed mission summary reports. Please insert values to view the report. 
Changes made on 👍 
modified:   UnoCPI/settings.py
modified:   home/templates/home/base_home.html
modified:   home/templates/reports/14ProjectPartnerInfo.html
modified:   home/templates/reports/projectreport.html
modified:   home/urls.py
modified:   home/views.py
modified:   requirements.txt

demo missions summart reports

---

UnoCPI/settings.py
account/templates/registration/login.html
home/static/css/Panel.css
home/templates/home/Countymap.html
home/templates/home/homepage.html
home/templates/home/projectmap.html
home/templates/reports/14ProjectPartnerInfo.html

Mission Area Chart Layout Fix, Academic Year Select2 Filter fix

Chart layout fix

---

home/forms.py
home/templates/home/ContactUs.html
home/templates/home/base_home.html
home/templates/home/contact_template.txt
home/templates/home/thanks.html
home/urls.py
home/views.py

Contact Us feature form functionality

ContactUs form functionality

---

home/templates/home/registration/campus_partner_user_register.html
home/templates/home/registration/community_partner_user_register.html
partners/templates/partners/campus_partner_user_update.html
partners/templates/registration/campus_partner_register.html
partners/templates/registration/community_partner_register.html
projects/templates/projects/Projectlist.html
projects/templates/projects/projectedit.html

 Frontend JS validations

---

home/templates/charts/engagementtypechart2.html
home/templates/charts/missionchart.html
home/templates/home/Admin_home.html
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/Dashboard_Extension.html
home/templates/home/admin_frame.html
home/templates/home/base_home.html
home/templates/reports/8CountOfUniqueCommunityPartner.html
home/views.py
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/views.py

Community Partner Project View and UI on Charts. public community report, unique report

Community Partner View proj fix and Style on charts

---

UnoCPI/settings.py
home/static/css/about.css
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/ContactUs.html
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/templates/home/thanks.html
home/templates/reports/14ProjectPartnerInfo.html
home/templates/reports/15EngagementTypeReport.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_public_view.html

Public Report (Hide, Show Filters) , Contact Us  Layout fix,

Ui sprint6 initial

---

UnoCPI/settings.py
home/static/css/about.css
home/static/css/footer.css
home/templates/import/uploadCampus.html
home/templates/import/uploadCampusDone.html
home/templates/import/uploadCommunity.html
home/templates/import/uploadCommunityDone.html
home/templates/import/uploadIncome.html
home/templates/import/uploadIncomeDone.html
home/templates/import/uploadProject.html
home/templates/import/uploadProjectDone.html

Updated the layout for Data Import Pages

Ui sprint6 map

---

home/views.py
media/campus_sample.csv
media/community_sample.csv

Added code to import conversion to county, income.
The upload process is very slow now, it takes 5 min for community data to upload. 
Coordinates, county, income are saved directly into the database now.

Import conversion to county, income

---

projects/filters.py
projects/forms.py
projects/templates/projects/SearchProject.html
projects/templates/projects/projectadd.html

Minor UI fixes-- on search and add projects

Manualtesting2

---

account/templates/registration/login.html
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/templates/home/registration/campus_partner_user_register.html
projects/templates/projects/Projectlist.html
projects/templates/projects/community_partner_projects.html
projects/templates/projects/projectedit.html
projects/views.py

Reverts uno-isqa-8950/uno-cpi#401

Revert " calculation field save and changes on project view campus/communit P…"

---

home/views.py
projects/forms.py
projects/templates/reports/community_private_view.html
projects/templates/reports/projects_private_view.html
projects/views.py

Layout for the two reports fixed.

Project and Community Report fixed.

---

home/dataload/initial_dataload.json

Just added JSON file to load lookup tables.
To load data, Please pull latest develop and just run these commands. 
python manage.py migrate
python manage.py makemigrations
python manage.py loaddata home/dataload/test.json

Dataload JSON file

---

home/models.py
partners/models.py

Please Review - Changes made for Campus Partner Registration Issue #484

484-Campus partner registration fix

---

partners/templates/registration/community_partner_register.html

Changed the address fields to have a consistent flow of address fields in "Register:Community Partner" form. 
The general flow of address fields determined is as follows
•	Physical Address
•	City
•	State
•	Zip
•	Country

564-community partner registration address consistency

---

projects/templates/projects/projectadd.html

Fixed the issue in Create Project Form

Ticket-500

---

projects/templates/projects/projectadd.html

#559  Fixed Address Reordering
Order being -
- Address Line 1
- City
- State
- Zipcode
- Country

#559 - Address Ordering in Project Create Form

---

projects/forms.py
projects/templates/projects/projectadd.html
university/models.py

#493 
The drop down for Activity Type - **Course** has the following options-
Other drop downs do not have additional options for Activity Type-

493 - Course Drop Down fix and Activity Type reorder

---

UnoCPI/settings.py

Fixing previous 476 pull request by moving middleware_classes ahead of middleware

Updating settings.py for https redirecting

---

home/models.py
home/templates/reports/14ProjectPartnerInfo.html
partners/forms.py
partners/templates/registration/campus_partner_register.html
partners/templates/registration/community_partner_register.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html

#561 Made cell phone not a required field & changed labels

---

UnoCPI/settings.py
requirements.txt

Fixing https redirect, part 3.

Anzalone 476 2

---

tests_scripts/Sprint 0/Project_Form_NoDescriptionRequired_Testcase.py

#497 
@EdemD , the test ran successfully for the Project Form, the description field is no longer mandatory in Project Forms

Test script kalpana

---

home/Partner_GEOJSON.py
home/Project_GEOJSON.py
home/static/js/Countymap.js
home/static/js/Districtmap.js
home/static/js/homepage.js
home/static/js/mapfilter.js
home/static/js/projectmapfilter.js
home/templates/home/GoogleMap_JSON.html
home/views.py
partners/views.py
projects/views.py

Updating Mapbox API token and Google Maps API key from Minh's to mine.

Anzalone API Updates

---

partners/templates/registration/community_partner_register.html

Fixed the non responsive buttons in Register Community Partner Page #558 
This was the issue before
Fixed now

558 - Fixed the non responsive buttons in Register Community Partners Form

---

projects/templates/projects/projectadd.html
projects/views.py

This resolves tickets 499, 560, and 562 by allowing for multiple mission areas and multiple:

Anzalone 499 560 562

---

projects/templates/projects/projectadd.html
university/models.py

#493  - migration warning fix and match by value "course" instead of "id"

493-Campus partner registration fix

---

CellPhoneNotRequired_TestScript_Pallavi.py

Label changes and cell phone no longer a mandatory field.

#561 Cell Phone no longer a  mandatory field

---

home/dataload/initial_dataload.json

The discontinued option is added to the dropdown

#508- added discontinued option to the dropdown

---

projects/templates/projects/Projectlist.html
projects/templates/projects/SearchProject.html

#518 Updated label and table width

---

partners/forms.py
partners/templates/partners/campus_partner_org_add.html
partners/templates/partners/campus_partner_org_profile.html
partners/templates/partners/campus_partner_user_profile.html
partners/templates/partners/campus_partner_user_update.html
partners/urls.py
partners/views.py
projects/templates/projects/projectadd.html

This pull request also moves the formsets in projects forms to the top.

#624 -  shashank

---

tests_scripts/Sprint1/Campus_Partner_User_emailduplication_Testscript.py

#486- campus partner email duplication test script

---

tests_scripts/Sprint1/addFunctionalityOnOrganizationsPage.pyComplete.py

Adding test script for ticket 624 - Doris

---

tests_scripts/Sprint1/removeButtonTesting.py

Creating pull request for Joseph

Created QA Test Script for #500 Ticket

---

home/templates/reports/15EngagementTypeReport.html
home/views.py

#458 Engagement-report-filter-fixed--pallavi

---

projects/forms.py
projects/templates/projects/projectadd.html
projects/views.py

Split mission on Project form into primary and secondary mission boxes

---

tests_scripts/Sprint2/ProjectMapVisibility.py

New automated test script created for the Visibility of the Project Map.

Created QA Test Script for #477 Ticket

---

home/templates/home/home_page.html

Commented out some parts of the Homepage that will be corrected in Sprint 3.

CMS updates for Sprint 2 Demo

---

home/templates/charts/engagementtypechart2.html
home/templates/charts/missionchart.html
home/templates/reports/14ProjectPartnerInfo.html
home/templates/reports/15EngagementTypeReport.html
projects/templates/projects/Projectlist.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_public_view.html

I updated all the reports and charts to have even spacing along the top.

ticket 649

---

home/templates/home/registration/campus_partner_user_register.html
home/templates/home/registration/community_partner_user_register.html
partners/forms.py
partners/templates/partners/campus_partner_user_update.html
partners/templates/registration/campus_partner_register_for_projects.html
partners/templates/registration/community_partner_register.html
partners/templates/registration/community_partner_register_for_projects.html
projects/templates/projects/projectadd.html
projects/templates/projects/projectedit.html

ADA compliance updates to validation error messages across forms.
- Updated HTML files to remove HTML validation scripts.
- Based on removed validations, updated form.py files to provide additional validations.

Updated files for ticket #551

---

projects/templates/reports/community_private_view.html
projects/templates/reports/projects_private_view.html

also updated community private view and projects private view

649 found 2 more to be updated

---

home/templates/home/partners.html

Responsiveness in Partners Page - Context Setting #488

Context Setting - Page Responsiveness #488

---

tests_scripts/Sprint2/Project_report_SCRIPT_pallavi.py

Campus Partner Project Report page when logged in
Project Report Page when NOT logged in

#629 Project_report_Script_Pallavi

---

home/templates/home/partners.html

Added definitions to the 4 entities and also got the popovers for campus partner and community partner working.

Adding partner definitions/popover

---

home/admin.py
home/models.py

You can view this table on the admin side

Datadefinitions table setup done

---

UnoCPI/settings.py
home/admin.py
partners/admin.py
projects/admin.py
requirements.txt
university/admin.py

Adding functionality to both import and export tables from apps: Home, Partners, Projects, and University.

Anzalone 534

---

projects/models.py

For ticket #724 updated projects/model.py to default Status field to "Active"

Set Status Field Default to Active

---

projects/models.py

This reverts commit ed250a5c6e759b0b25697b2e118da3146816213a, reversing
changes made to 3412eaa39c294742b5258eb5250093fd8c246a21.

Revert "Merge pull request #742 from uno-isqa-8950/724-Nabity"

---

home/dataload/data_definition.json
home/templates/home/DataDefinitions.html
home/urls.py
home/views.py

Added pop up messages to get the data associated with Campus Partner and Community Partners.

#475 - Data Definitions in Partners Page

---

home/templates/home/partners.html

Missed to commit Partners page that shows data definitions

DataDefinition

---

home/templates/reports/14ProjectPartnerInfo.html
home/templates/reports/15EngagementTypeReport.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html

#727 Reset filters button-- Pallavi

---

projects/templates/projects/projectadd.html

Created a java script on the projectadd.html file to validate a Primary Mission Area is provided for new projects when they are submitted. Updated formset html for Primary Mission to call javascript function.

Require Primary Mission Area - New Projects

---

home/templates/reports/ProjectPartnerInfo.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html

Changes made in Community Partner Types to name the labels uniformly

Data Definition - Community Partner Labels

---

home/dataload/data_definition.json
home/templates/home/Community_Home.html
projects/templates/projects/Projectlist.html
projects/templates/projects/SearchProject.html
projects/templates/projects/community_partner_projects.html
projects/views.py

Data Definition section for a logged in Campus Partner users -
1. My Projects Page
The table is more responsive and box shadow removed
2. All Projects Page

Data Definition - Campus Partner and Community Partner Project Reports

---

home/static/js/googlehomepage.js
home/templates/home/googlehomepage.html

Updated Community Partner Map using Google Maps.

Anzalone 701

---

home/templates/home/partners.html

Changed some alignments for User Contexts, associated with #726

Context Page - Alignment of buttons and css issues fixed

---

home/static/js/googlemap.js
home/templates/home/googlemap.html

Updates to Community Partner Type Map using Google Maps:

Anzalone 737

---

projects/templates/projects/Projectlist.html
projects/templates/projects/projectadd.html
projects/templates/projects/projectadd_done.html
projects/views.py

Data definitions for Create Project Page and removal of shadows

dataDefinitions

---

home/templates/charts/engagementtypechart2.html
home/templates/reports/ProjectPartnerInfo.html
projects/templates/projects/Projectlist.html
projects/templates/reports/projects_public_view.html

Ruthie 528 fixes

---

home/templates/home/Dashboard_Extension.html

Changes to the navbar to maps.

navbar changes

---

home/static/js/googlehomepage.js
home/static/js/googlemap.js

Changing the default zoom level.

Jerrodanzalone zoomies

---

projects/models.py
projects/templates/projects/projectadd.html

Reverting project form to Sprint 2.

Anzalone projectadd

---

home/static/js/googleprojectmapfilter.js
home/templates/home/googleprojectmap.html
home/views.py

Google project map fix

---

home/static/js/googlehomepage.js
home/templates/home/googlehomepage.html

Updates to the Community Partner Map to add clustering and search functionality.

Anzalone map updates

---

home/static/js/googleDistrictmap.js
home/static/js/googleprojectmapfilter.js

Anzalone 829

---

projects/templates/projects/projectadd.html

#837 -  To have a common layout on the Project Create Form and removal of Mission Area button to add another secondary Mission Area

Create Project Form - To remove additional Mission Area button

---

home/filters.py
home/templates/charts/missionchart.html
home/templates/reports/ProjectPartnerInfo.html
home/views.py
projects/models.py

Fixed the Mission Area Reports and Mission Area Charts. Added extra college name filter

#464, #465, #757, #826

---

projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/views.py

added college filter and campus filter without cascading filters

added filters for community partner reports

---

home/views.py
partners/views.py
projects/views.py

Removal of Print statements to removal additional time loads.
@vbhat0891  please review
@jerrodanzalone  - we might have to test this while deploying to cat, probably this wednesday during the dry run

Generic - No Ticket- Removal of all Print Statements from Views

---

home/templates/home/Admin_home.html
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/Countymap.html
home/templates/home/CpiHome.html
home/templates/home/Dashboard_Extension.html
home/templates/home/Districtmap.html
home/templates/home/Map_Home.html
home/templates/home/base_home.html
home/templates/home/googleDistrictmap.html
home/templates/home/googlehomepage.html
home/templates/home/googlemap.html
home/templates/home/googleprojectmap.html
home/templates/home/home_page.html
home/templates/home/homepage.html
home/templates/home/okMap.html
home/templates/home/projectmap.html
partners/templates/partners/campus_partner_user_profile.html
partners/templates/partners/campus_partner_user_update.html
partners/templates/partners/community_partner_user_profile.html
partners/templates/partners/community_partner_user_update.html

Per Sprint 3 ADA ticket #735 there is a need for <img> tags to have an alt attribute populated.

Update IMG Tag Attributes

---

home/templates/charts/missionchart.html
partners/forms.py
partners/templates/partners/campus_partner_org_contact.html
partners/templates/partners/campus_partner_org_profile.html
partners/templates/partners/community_partner_org_contact.html
partners/templates/partners/community_partner_org_mission.html
partners/templates/partners/community_partner_org_profile.html

Fixed Partner Organization Pages for both campus and community Partner Users

#839  community organization vineeth

---

home/blocks.py
home/models.py
home/templates/blocks/column.html
home/templates/blocks/three_column_block.html
home/templates/blocks/two_column_block.html
home/templates/home/blog_index_page.html
home/templates/home/blog_page.html
home/templates/home/home_page.html
home/templates/home/include/footer_text.html
home/templates/home/include/header-hero.html
home/templates/home/include/header-index.html
home/templates/home/include/header.html
home/templates/includes/footer.html
home/templates/includes/head.html
home/templates/includes/header.html
home/templates/includes/messages.html

Anzalone cms updates

---

home/Partner_GEOJSON.py
home/Project_GEOJSON.py

Script to generate geojson files

Script to generate GEOJSON

---

home/static/js/googleDistrictmap.js

This pull request is to address #875

Close infowindow on click on another marker fix

---

home/templates/home/home_page.html

Updating hover over color to be red.

Updating hyperlink hover over

---

home/templates/home/home_page.html

To show updated footer for demo:

Anzalone cms

---

Partner_GEOJSON.py
Project_GEOJSON.py
UnoCPI/Partner_GEOJSON.py
UnoCPI/Project_GEOJSON.py
UnoCPI/jobs.py
account/templates/registration/login.html
jobs.py

Centered login button and made it responsive -

Login Button Centered

---

home/templates/charts/engagementtypechart2.html
home/templates/charts/missionchart.html
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/Districtmap.html
home/templates/home/base_home.html
home/templates/home/googleDistrictmap.html
home/templates/home/googlehomepage.html
home/templates/home/googlemap.html
home/templates/home/googleprojectmap.html
home/templates/home/homepage.html
home/templates/home/partners.html
home/templates/reports/EngagementTypeReport.html
home/templates/reports/ProjectPartnerInfo.html
partners/templates/partners/campus_partner_org_profile.html
partners/templates/partners/campus_partner_org_update.html
partners/templates/partners/community_partner_org_add.html
partners/templates/partners/community_partner_org_profile.html
projects/templates/projects/projectadd.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html

all the headers and buttons are changed to #333333, the filters and accents are now #bbbbbb
also removed extra grey header and grey outline on map headers

529 ruthie

---

home/templates/home/googlemap.html

Fix for the community partner type map - updated the API key

---

home/templates/charts/engagementtypechart2.html
home/templates/charts/missionchart.html
home/templates/reports/8CountOfUniqueCommunityPartner.html
home/templates/reports/EngagementTypeReport.html
home/templates/reports/ProjectPartnerInfo.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html

#957 Default filters hidden

---

projects/templates/projects/projectadd.html

CSS Fixes for the Create Project Form

---

UnoCPI/settings.py
requirements.txt

Adding admin module to track changes

---

home/templates/charts/engagementtypechart2.html
home/templates/charts/missionchart.html
home/templates/reports/EngagementTypeReport.html
home/templates/reports/ProjectPartnerInfo.html
home/templates/tags/engagement_types_chart_snippet.html
home/templates/tags/engagement_types_report_snippet.html
home/templates/tags/mission_areas_chart_snippet.html
home/templates/tags/mission_areas_report_snippet.html
home/templatetags/register_tags.py

Adding Snippets for remaining chart and report descriptions.

CMS Snippets

---

Partner_GEOJSON.py
Project_GEOJSON.py
UnoCPI/Partner_GEOJSON.py
UnoCPI/Project_GEOJSON.py
home/Partner_GEOJSON.py
home/Project_GEOJSON.py
home/templates/home/GoogleMap_JSON.html
home/templates/home/communityPartnerType.html
home/templates/home/legislativeDistrict.html
home/templates/home/projectMap.html
partners/views.py
projects/views.py

Changes to hide Google Maps API key from public view

Changes to hide Google Maps API throughout

---

home/static/js/legislativeDistrict.js

I have refactored the code to allow users to add 3 additional mission areas apart from the default mission areas.
Also, updated the color categories to Power BI color codes. Thanks to @caadler for sharing the colors used in Power BI. I will extend it to others based on the feedback.

Legislative district map additional mission area/color category update

---

home/static/js/communityPartner.js
home/views.py

Testing out cascading filters on Community Partners map

Anzalone cascade

---

projects/templates/reports/community_public_view.html

Community Partner Public report -- filter alignment fix

---

projects/admin.py

Fixing import-export functionality within the admin projects tables.

Updating to fix broken import-export

---

home/forms.py
partners/forms.py
partners/templates/registration/campus_partner_register_done.html
partners/templates/registration/community_partner_register_done.html

Shadow removal after community partner registration and updating URL field in website

Community partner registration

---

home/templates/home/partners.html
home/templates/home/registration/inviteCommunityPartner.html

Updating Text on Community Partner User Invite

---

account/templates/account/CommunityPartner_Invite_email.html
account/templates/account/acc_active_email.html
home/templates/home/Admin_home.html
home/templates/home/Campus_Home.html
home/templates/home/Community_Home.html
home/templates/home/base_home.html
home/templates/home/communityPartner.html
home/templates/home/communityPartnerType.html
home/templates/home/legislativeDistrict.html
home/templates/home/projectMap.html

Updating CPI email address to partnerships@unomaha.edu.

Updating CPI email address

---

home/templates/home/home_page.html

...for homepage to enable it to be more responsive elsewehere.

Making separate footer, etc.

---

partners/forms.py
partners/templates/registration/community_partner_register.html

#1174 Catch_errors_Community_partner_address_form

---

partners/forms.py
partners/templates/registration/community_partner_register.html

#1174 catch_errors_community_partner_address

---

home/templates/home/home_page.html

Fixing empty space below embedded content in CMS.

CMS update

---

partners/forms.py
partners/templates/partners/community_partner_org_add.html
partners/templates/partners/community_partner_org_profile.html
partners/templates/partners/community_partner_org_update.html
partners/templates/partners/community_partner_user_profile.html
partners/templates/partners/community_partner_user_update.html

Community Partner Organizaton Profile update -
Community partner user profile update -

Profile updates for Community Partner

---

projects/templates/projects/createProject.html

Added Missing validation errors

Validation Error - Projects

---

UnoCPI/settings.py

Turning off debug for production

Update settings.py to turn off debug

---

home/forms.py

Validation Error message updates - Campus Partner User

---

partners/templates/partners/checkCommunityPartner.html

Fixing issue with Community Partner button

---

home/forms.py

Fix for Community Partner User invite

Community Partner User invite error fix

---

account/templates/account/CommunityPartner_Invite_email.html
home/views.py

Community Partner User Invite- 
Campus Partner User Registration -

Updating sender for Campus/Community Partner User registration

---

home/forms.py

Updated for both Campus and Community Partner User Profiles -

Campus and Community Partner Profile update

---

home/forms.py

Reverts uno-isqa-8950/uno-cpi#1351

Revert "Campus and Community Partner Profile update"

---

account/templates/registration/login.html

Label change for Campus Partner User Registration in Login Page

Label change for Campus Partner User Registration 

---

partners/templates/partners/checkCommunityPartner.html

Fixing second check buttong

---

home/templates/home/home_page.html

Added extra spacing between dotted lines.

Sprint 1 karthik

---

.gitignore
home/templates/home/base_home.html
home/templates/home/home_page.html
projects/templates/projects/createProject.html
projects/templates/reports/community_public_view.html
projects/views.py
requirements.txt

Reverts uno-isqa-8950/uno-cpi#1560

Revert "Sprint 1 karthik"

---

.gitignore
home/templates/home/base_home.html
home/templates/home/home_page.html
projects/templates/projects/createProject.html
projects/templates/reports/community_public_view.html
projects/views.py
requirements.txt

Reverts uno-isqa-8950/uno-cpi#1564

Revert "Sprint 2_ project changes"

---

.gitignore
home/templates/home/base_home.html
home/templates/home/home_page.html
projects/templates/projects/createProject.html
projects/templates/reports/community_public_view.html
projects/views.py
requirements.txt

Reverts uno-isqa-8950/uno-cpi#1566

Revert "Revert "Sprint 2_ project changes""

---

home/static/js/communityPartner.js
home/static/js/communityPartnerType.js
home/static/js/legislativeDistrict.js
home/static/js/projectMap.js

Changed 4 JS file and replaced the urls.
modified:   home/static/js/communityPartner.js
modified:   home/static/js/communityPartnerType.js
modified:   home/static/js/legislativeDistrict.js
modified:   home/static/js/projectMap.js

move github google js-marker cluster image to AWS

---

home/static/css/base_home.css
home/templates/home/home_page.html

Fixed Homepage banner resize
home_page.html
base_home.css

 home page hero banner fix

---

home/static/css/base_home.css
home/templates/home/home_page.html

Home page hero banner fix.
Files modified
home/static/css/base_home.css
home/templates/home/home_page.html

homepagebanner fix

---

home/static/css/base_home.css
home/templates/home/home_page.html

Html and css change to hero image
home/templates/home/home_page.html
home/static/css/base_home.css

Herobannerfeature

---

home/static/css/base_home.css
home/templates/home/home_page.html

home/static/css/base_home.css
home/templates/home/home_page.html

removed commented code from homepage.html and base_home.css

---

home/views.py

issue address chart fix

---

home/views.py

Reverting changes in Issue Chart

issue address chart fix_old code

---

Aptfile

added new aptfile including xmlsec package required for apt buildpack

add aptfile to support apt buildback

---

account/views.py

remove external xmlsec from app dir

remove external xmlsec from app dir

---

Aptfile

update apt file
remove existing buildpack from heroku
installed new buildpacks in heroku

update apt file

---

requirements.txt

trigger auto deploy since removed multi buildpack from heroku

update requirement file and remove multi build pack

---

requirements.txt

update django filter version in requirement.txt

update django filter version 2.3

---

requirements.txt

update requirement.txt for django-filters

update django filter

---

account/views.py

Saml encrypt

---

account/templates/registration/login.html
account/views.py
home/templates/home/Admin_home.html
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/templates/home/partners.html
home/templates/includes/header.html
partners/views.py
projects/templates/projects/community_partner_home.html

Change 1:
Screenshot 1 – change message to:
You are not registered as a CEPI user. Please contact the administrator for access by emailing partnerships@unomaha.edu and identify what campus partner you are affiliated with.
Change 2:
a) Remove the ‘Campus Partner User Registration’ form from all pubic pages.
·         https://uno-cpi.herokuapp.com/partners/
·         https://uno-cpi-herokuapp.com/account/login-Page/
b) Remove ‘Invite a Community Partner User’ from page
Show both forms in the admin drop-down only.
Change 3:
Remove Organizational Detail: https://uno-cpi.herokuapp.com/partners/profile/orgprofile/ and make it admin only. The change will allow Admin to view both campus and community partners.

changes requested by K, adjust the links and update error message

---

home/templates/home/partners.html

remove space from image file path in partner.html

remove space from img path

---

runtime.txt

Updated runtime.txt with python version = 3.9.7

Updated runtime.txt

---

cypress/e2e/maps/ProjectMapsPublicUser.cy.js
projects/templates/reports/projects_public_view.html

- Fixed the reset issue when user not login.
- Added cypress script for projects_maps.

Reset and projectMapsPublicUser

---

.gitignore
account/views.py
cypress/e2e/maps/ProjectMapsPublicUser.cy.js
demo_doc.txt
home/templates/home/recent_changes.html
home/urls.py
home/views.py
package-lock.json
projects/models.py
projects/templates/projects/allProjects.html
projects/templates/reports/projects_public_view.html
projects/views.py

demo: creating documentation for version control to share with team mates. Changes and branch will be discarded.

Sp23 simran testbranch

---

projects/models.py
projects/views.py

feat: mansi SP2 code, fix: default 0
Mansi's updates:
1. recentchanges view, html, url
2. Apply filter button
Simran's updates:
1. removed default = 0 option from  total_uno_students, total_uno_hours

feat: mansi SP2 code, fix: default 0

---

cypress/support/commands.js

This commit is for Projects Map automation testing.

Sp23 naga reset

---

cypress/e2e/analytics/charts/engagementTypesChartsCampusPartnerUser.cy.js
home/templates/charts/engagementtypechart2.html

Updated engagement type chart and added data-cy attribute

testscript:engagementtypechart and data-cy addition

---

home/models.py
home/templates/home/base_home.html
home/views.py
partners/templates/registration/campus_partner_register_for_projects.html
partners/urls.py
partners/views.py
projects/models.py
projects/views.py

*Added fix for Focus area report, Engagement types report, Community types report
*Admin side fix for unique together, note: from UI duplicates can still be added - that section is in-progress,

fix: reports, admin:unique_together

---

cypress/e2e/analytics/charts/focusAreaChartsAdmin.cy.js
cypress/e2e/analytics/charts/focusAreaChartsCampusPartner.cy.js
cypress/e2e/analytics/charts/projectAndPartnerTrendsChartsAdmin.cy.js
cypress/fixtures/users.json
home/templates/charts/focusareaanalaysis.html
home/templates/charts/trendreport.html
home/templates/home/base_home.html

Test Scripts for: 
Focus Area Chart Campus Partner User
Focus Area Chart Admin Partner User
Project and Partner Trend Chart Admin User
data-cy references

Analytics - Chart Test Scripts

---

cypress/e2e/analytics/charts/focusAreaChartsAdmin.cy.js
cypress/e2e/analytics/charts/focusAreaChartsCampusPartner.cy.js
home/templates/charts/missionchart.html

data-cy element for mission-chart.html
Fix error for Focus Area test scripts

Add data-cy element

---

cypress/e2e/administrator/adminView/home/contact.cy.js
cypress/e2e/administrator/adminView/home/dataDefinition.cy.js
cypress/e2e/administrator/adminView/home/householdIncome.cy.js
cypress/e2e/administrator/adminView/home/missionAreas.cy.js
cypress/e2e/administrator/adminView/home/resources.cy.js
cypress/e2e/administrator/adminView/home/users.cy.js
cypress/e2e/administrator/adminView/partners/campusPartner.cy.js
cypress/e2e/administrator/adminView/partners/campusPartnerUser.cy.js
cypress/e2e/administrator/adminView/partners/cecBuildingPartner.cy.js
cypress/e2e/administrator/adminView/partners/cecPartnerStatus.cy.js
cypress/e2e/administrator/adminView/partners/communityPartnerMissions.cy.js
cypress/e2e/administrator/adminView/partners/communityPartnerUsers.cy.js
cypress/e2e/administrator/adminView/partners/communityPartners.cy.js
cypress/e2e/administrator/adminView/partners/communityType.cy.js
cypress/e2e/administrator/adminView/partners/partnerStatus.cy.js
cypress/e2e/administrator/adminView/projects/academicYears.cy.js
cypress/e2e/administrator/adminView/projects/activityTypes.cy.js
cypress/e2e/administrator/adminView/projects/engagementActivityTypes.cy.js
cypress/e2e/administrator/adminView/projects/engagementTypes.cy.js
cypress/e2e/administrator/adminView/projects/missionSubCategory.cy.js
cypress/e2e/administrator/adminView/projects/projects.cy.js
cypress/e2e/administrator/campusPartner/campusPartnerOrganizations.cy.js
cypress/e2e/administrator/cms/cms.cy.js
cypress/e2e/administrator/userRegistration/campusPartnerUserRegistration.cy.js
cypress/e2e/campusPartner/profile/profileDetails.cy.js

Updating Cypress scripts

---

cypress/e2e/analytics/charts/focusAreaChartsAdmin.cy.js
cypress/e2e/analytics/charts/focusAreaChartsCampusPartner.cy.js
cypress/e2e/analytics/charts/partnershipIntensityAnalysisChartsAdminUser.cy.js
cypress/e2e/analytics/charts/partnershipIntensityAnalysisChartsCampusPartnerUser.cy.js
cypress/e2e/analytics/charts/projectAndPartnerTrendsChartsAdmin.cy.js
cypress/e2e/maps/communityPartnersMapsAdministratorUser.cy.js

Adjust test scripts for charts, maps
- partnershipintensity charts for admin and campus user
- focus area charts for admin and campus user
- community partners maps for admin users

Test scripts fix

---

cypress/e2e/analytics/reports/focusAreaReportsAdministrator.cy.js
cypress/e2e/analytics/reports/projectsReportsPublicUser.cy.js
home/templates/reports/ProjectPartnerInfo_admin.html
home/templates/reports/ProjectPartnerInfo_public.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html
projects/templates/reports/projectsprivatetableview.html
projects/templates/reports/projectspublictableview.html

Data cy element addition for Sprint 4 Deliverables
projectspublictableview.html
projects_public_view.html
projectsprivatetableview.html
projects_private_view.html
ProjectPartnerInfo_admin.html
ProjectPartnerInfo_public.html

Sp23 sprint4 qa branch karpagam

---

projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html

Data-cy element added wherever necessary , and tested in local

Community Private View and Community Public View Data-cy additions

---

cypress/e2e/maps/ProjectMapsAdminUser.cy.js
cypress/e2e/maps/ProjectMapsPublicUser.cy.js
cypress/e2e/maps/cityDistrictMapsAdminUser.cy.js
cypress/e2e/maps/cityDistrictMapsCampusUser.cy.js
cypress/e2e/maps/cityDistrictMapsPublicUser.cy.js
home/templates/home/Dashboard_Extension.html

Added data-cy to the code wherever script needed.

Sp23 sprint4 q abranch naga data cy refresh

---

cypress/e2e/analytics/charts/engagementTypesChartsAdminUser.cy.js
cypress/e2e/registerPartners/registerPartnerPublicUser.cy.js
home/templates/home/partners.html
package-lock.json
package.json
partners/templates/registration/campus_partner_register.html
partners/templates/registration/campus_partner_register_done.html
partners/templates/registration/campus_partner_register_for_projects.html

Updated test script for register campus partner admin user

Sp23 sprint4 bhuvana

---

projects/models.py

Project name parenthesis bug fix

---

requirements.txt

@SachinPawaskarUNO 
I will be installing SAML packages separately on heroku shell using --force-reinstall --use-pep517 to test on DEV. This method works on local env.

removing SAML related packages

---

Procfile
requirements.txt

@SachinPawaskarUNO 
1. updated requirements.txt
2. modified Procfile to test order of execution of requirements on Dev (will check build logs to see how it goes)

SP23_Sprint5 PR#2 [for SAML]

---

Procfile
requirements.txt

- rollback: build from Procfile
- reorder: requirements.txt

Sp23 sprint5 PR#5

---

cypress.config.js
cypress/e2e/analytics/reports/focusAreaReportsAdministrator.cy.js
cypress/e2e/analytics/reports/focusAreaReportsCampusPartnerUser.cy.js
cypress/e2e/analytics/reports/focusAreaReportsPublicUser.cy.js
cypress/e2e/analytics/reports/projectsReportsPublicUser.cy.js
cypress/e2e/campusPartner/profile/profileDetails.cy.js
cypress/e2e/cepiProject/cepiTestPriority4.cy.js
cypress/e2e/maps/cityDistrictMapsAdminUser.cy.js
cypress/e2e/maps/cityDistrictMapsCampusUser.cy.js
cypress/e2e/maps/cityDistrictMapsPublicUser.cy.js
cypress/e2e/maps/projectMapsAdminUser.cy.js
cypress/e2e/maps/projectMapsCampusPartnerUser.cy.js
cypress/e2e/maps/projectMapsPublicUser.cy.js
requirements.txt

bumped down some package versions to test on DEV.
I rolled back CAT env to version from Feb 24 and SAML auth worked on it.

Sp23 sprint5

---

cypress/e2e/maps/projectMapsAdminUser.cy.js
cypress/e2e/maps/projectMapsCampusPartnerUser.cy.js
cypress/e2e/maps/projectMapsPublicUser.cy.js
requirements.txt

test: bumped up versions for testing heroku stack 22
@SachinPawaskarUNO

Sp23 sprint6

---

.circleci/config.yml

fixed failed test cases in circle ci

Circle CI Updates - Updated code config.yaml file

---

cypress.config.js
package.json

Enabled experimentalMemoryManagement in  Cypress.config file and added cypress headless mode.

Updated Cypress.config and package.json files - Resolved Circle CI Memory issue

---

.circleci/config.yml

Updated circle ci config.yml file.

Added Create User Automated Script

---

home/templates/reports/EngagementTypeReport.html
home/templates/reports/ProjectFocusTopicInfo.html
home/templates/reports/ProjectPartnerInfo.html
home/templates/reports/ProjectPartnerInfo_admin.html
home/templates/reports/ProjectPartnerInfo_public.html
partners/templates/registration/campus_partner_register.html
projects/templates/projects/allProjects.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_private_view.html
projects/templates/reports/projects_public_view.html
projects/templates/reports/projectsprivatetableview.html
projects/templates/reports/projectspublictableview.html
requirements.txt

- mansi's code changes
- django bumped to 4.1.9

Sp23 sprint6 PR#3

---

home/templates/charts/missionchart.html

Updated Focus Area chart with correct variable.

Updated Focus Area chart

---

UnoCPI/settings.py
UnoCPI/sqlfiles.py
cypress/e2e/homepage/homepageAdministrator.cy.js
cypress/e2e/homepage/homepageCampusPartnerUser.cy.js
cypress/e2e/homepage/homepagePublicUser.cy.js
home/static/js/cityDistrict.js
home/static/js/communityPartner.js
home/static/js/legislativeDistrict.js
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/views.py
projects/templates/projects/editProject.html
projects/templates/reports/projectsprivatetableview.html
projects/views.py
requirements.txt

- Fixed academic year queries
- Removed menu items from navigation bar
- Fixed  academic year issue while editing project saved as Draft.
- Fixed academic year order in maps-projects
- Fixed duplicate project issue
- Updated table view as default in Project report.
- Included Bump certifi from 2022.12.7 to 2023.7.22 #2647
-Included Bump django from 4.1.9 to 4.1.10 #2643
-Bump requests from 2.28.2 to 2.31.0 #2621

SU23 CEPI Issue list fix_2

---

cypress/e2e/homepage/homepageAdministrator.cy.js
cypress/e2e/homepage/homepageCampusPartnerUser.cy.js
cypress/e2e/homepage/homepagePublicUser.cy.js
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
projects/templates/reports/projectsprivatetableview.html
projects/templates/reports/projectspublictableview.html

- Updated comments for removing specific maps and charts from navigation menu
- Removed "All Projects" from Navigation Menu
- Updated public view reports to have all columns while extracting project report.
- Provided "Edit" button for Admin/super user to edit the projects from front end.
- Made Maps navigation menu consistent for both public and logged in user.

Issue2630,2651 and Navigation menu

---

cypress/e2e/homepage/homepagePublicUser.cy.js
home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/templates/home/partners.html
projects/templates/projects/adminconfirm.html
projects/templates/projects/confirmAddProject.html
projects/views.py

- Removed 'Partners' navigation Menu for public user
- Included "Add Community partner" to the "Partners" tab for both campus user and admin user
- Fixed the Community Partner report hyper link to navigate to the projects.
- Removed "Projects-->All Projects" for all users in Dashboard _Extension.html

SU23 CEPI Issue fix 5

---

cypress/e2e/analytics/reports/engagementTypesReportsAdministrator.cy.js
cypress/e2e/analytics/reports/engagementTypesReportsCampusPartnerUser.cy.js
cypress/e2e/analytics/reports/engagementTypesReportsPublicUser.cy.js
cypress/e2e/analytics/reports/focusAreaReportsAdministrator.cy.js
cypress/e2e/analytics/reports/focusAreaReportsCampusPartnerUser.cy.js
cypress/e2e/analytics/reports/focusAreaReportsPublicUser.cy.js
home/templates/reports/EngagementTypeReport.html
home/templates/reports/ProjectFocusTopicInfo.html
home/templates/reports/ProjectPartnerInfo_admin.html
home/templates/reports/ProjectPartnerInfo_public.html
projects/templates/reports/community_private_view.html
projects/templates/reports/community_public_view.html

Made project table view default in all reports.

Issue Fix -Default Table View

---

home/templates/home/Dashboard_Extension.html
home/templates/home/base_home.html
home/templates/home/partners.html
home/templates/reports/ProjectFocusTopicInfo.html
home/templates/reports/ProjectPartnerInfo.html
home/templates/reports/ProjectPartnerInfo_public.html
projects/models.py
projects/templates/reports/community_public_view.html
projects/templates/reports/projects_public_view.html
projects/templates/reports/projectsprivatetableview.html
projects/templates/reports/projectspublictableview.html

1. Revise this page: [Community Partnership Initiative (unomaha.edu)](https://cepi.unomaha.edu/partners/)
- Change heading in gray bar to "Add a Community Partner"
- Remove the register campus partner button
- Remove the language under the photo
- Edit the language under the buttons to read: Campus users with access to enter new projects into this tool can also add a new community partner. Please review the Community Partners Report before adding a new organization - filtering by "All Academic Years" in your search. To request a new Campus Partner, please email the Office of Engagement at unoengagement@unomaha.edu.
- Contact us button - change the email to unoengagement@unomaha.edu
2. Update Date functionality is included
3. Project Name field is also included in public reports
4. …

Partner Page changes and GA tag inclusion

---

UnoCPI/settings.py
home/templates/404.html
home/templates/500.html
saml/settings.json

- Add allowed host
- Add error 404 and 500 page

Fix security bug
